##### Server config #####
server:
  port: 8084

##### LOGGING CONFIGS #####
logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE