on: [push]
name: sophos backend ci workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@develop
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{  }}
